-- Ruralitos: esquema remoto inicial para una aplicacion Android offline-first.
-- La base local cifrada es la fuente inmediata; Supabase sincroniza y respalda.

create extension if not exists pgcrypto with schema extensions;

-- ---------------------------------------------------------------------------
-- Funciones comunes de auditoria y sincronizacion
-- ---------------------------------------------------------------------------

create or replace function public.actualizar_marca_tiempo()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.actualizar_version_sync()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  new.version := old.version + 1;
  return new;
end;
$$;

create or replace function public.uuid_seguro(valor text)
returns uuid
language plpgsql
immutable
set search_path = ''
as $$
begin
  return valor::uuid;
exception when others then
  return null;
end;
$$;

revoke all on function public.actualizar_marca_tiempo() from public;
revoke all on function public.actualizar_version_sync() from public;
grant execute on function public.uuid_seguro(text) to authenticated;

-- ---------------------------------------------------------------------------
-- Identidad, organizaciones, establecimientos y roles
-- ---------------------------------------------------------------------------

create table public.perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  cedula text,
  nombres text not null default '',
  cargo text not null default '',
  correo text not null default '',
  telefono text not null default '',
  pin_local_habilitado boolean not null default false,
  creado_en timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint perfiles_cedula_formato check (
    cedula is null or cedula ~ '^[0-9]{10,13}$'
  ),
  constraint perfiles_nombres_longitud check (char_length(nombres) <= 160),
  constraint perfiles_cargo_longitud check (char_length(cargo) <= 120),
  constraint perfiles_correo_longitud check (char_length(correo) <= 254),
  constraint perfiles_telefono_longitud check (char_length(telefono) <= 30)
);

create unique index perfiles_cedula_unica
  on public.perfiles (cedula)
  where cedula is not null;

create table public.establecimientos_salud (
  id bigint generated by default as identity primary key,
  codigo_uo text not null unique,
  nombre_centro_salud text not null,
  institucion_sistema text not null,
  provincia_codigo_localizacion text not null,
  provincia text not null,
  canton_codigo_localizacion text not null,
  canton text not null,
  parroquia_codigo_localizacion text not null,
  parroquia text not null,
  sector text not null,
  area_numero text not null,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index establecimientos_nombre_idx
  on public.establecimientos_salud using gin (to_tsvector('simple', nombre_centro_salud));
create index establecimientos_localizacion_idx
  on public.establecimientos_salud (provincia_codigo_localizacion, canton_codigo_localizacion, parroquia_codigo_localizacion);

create table public.organizaciones (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  codigo text not null unique,
  activo boolean not null default true,
  creado_por uuid not null default auth.uid() references auth.users(id) on delete restrict,
  creado_en timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint organizaciones_nombre_longitud check (char_length(btrim(nombre)) between 3 and 120),
  constraint organizaciones_codigo_formato check (codigo ~ '^[A-Z0-9_-]{3,30}$')
);

create table public.miembros_organizacion (
  id uuid primary key default gen_random_uuid(),
  organizacion_id uuid not null references public.organizaciones(id) on delete cascade,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  establecimiento_id bigint references public.establecimientos_salud(id) on delete set null,
  rol text not null default 'MEDICO',
  activo boolean not null default true,
  creado_por uuid default auth.uid() references auth.users(id) on delete set null,
  creado_en timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint miembros_rol_valido check (rol in ('ADMIN', 'MEDICO', 'ESTADISTICA')),
  constraint miembros_usuario_unico unique (organizacion_id, usuario_id)
);

create index miembros_usuario_idx
  on public.miembros_organizacion (usuario_id, activo);
create index miembros_establecimiento_idx
  on public.miembros_organizacion (establecimiento_id)
  where establecimiento_id is not null;

create table public.invitaciones_organizacion (
  id uuid primary key default gen_random_uuid(),
  organizacion_id uuid not null references public.organizaciones(id) on delete cascade,
  correo text,
  rol text not null default 'MEDICO',
  establecimiento_id bigint references public.establecimientos_salud(id) on delete set null,
  codigo_hash bytea not null unique,
  expira_en timestamptz not null,
  usado_en timestamptz,
  usado_por uuid references auth.users(id) on delete set null,
  creado_por uuid not null default auth.uid() references auth.users(id) on delete cascade,
  creado_en timestamptz not null default now(),
  constraint invitaciones_rol_valido check (rol in ('ADMIN', 'MEDICO', 'ESTADISTICA')),
  constraint invitaciones_correo_longitud check (correo is null or char_length(correo) <= 254)
);

create index invitaciones_vigentes_idx
  on public.invitaciones_organizacion (organizacion_id, expira_en)
  where usado_en is null;

create trigger perfiles_actualizar_marca
before update on public.perfiles
for each row execute function public.actualizar_marca_tiempo();

create trigger establecimientos_actualizar_marca
before update on public.establecimientos_salud
for each row execute function public.actualizar_marca_tiempo();

create trigger organizaciones_actualizar_marca
before update on public.organizaciones
for each row execute function public.actualizar_marca_tiempo();

create trigger miembros_actualizar_marca
before update on public.miembros_organizacion
for each row execute function public.actualizar_marca_tiempo();

-- El perfil se crea automaticamente al registrar una cuenta en Supabase Auth.
create or replace function public.crear_perfil_nuevo_usuario()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.perfiles (id, cedula, nombres, cargo, correo, telefono)
  values (
    new.id,
    nullif(btrim(new.raw_user_meta_data ->> 'cedula'), ''),
    coalesce(nullif(btrim(new.raw_user_meta_data ->> 'nombres'), ''), ''),
    coalesce(nullif(btrim(new.raw_user_meta_data ->> 'cargo'), ''), ''),
    coalesce(new.email, ''),
    coalesce(nullif(btrim(new.raw_user_meta_data ->> 'telefono'), ''), '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create or replace function public.sincronizar_correo_perfil()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.perfiles
     set correo = coalesce(new.email, '')
   where id = new.id;
  return new;
end;
$$;

revoke all on function public.crear_perfil_nuevo_usuario() from public;
revoke all on function public.sincronizar_correo_perfil() from public;

create trigger ruralitos_auth_usuario_creado
after insert on auth.users
for each row execute function public.crear_perfil_nuevo_usuario();

create trigger ruralitos_auth_correo_actualizado
after update of email on auth.users
for each row
when (old.email is distinct from new.email)
execute function public.sincronizar_correo_perfil();

-- Estas funciones evitan recursion en las politicas RLS de membresias.
create or replace function public.es_miembro(p_organizacion_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
      from public.miembros_organizacion m
     where m.organizacion_id = p_organizacion_id
       and m.usuario_id = (select auth.uid())
       and m.activo
  );
$$;

create or replace function public.es_admin(p_organizacion_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
      from public.miembros_organizacion m
     where m.organizacion_id = p_organizacion_id
       and m.usuario_id = (select auth.uid())
       and m.activo
       and m.rol = 'ADMIN'
  );
$$;

create or replace function public.puede_editar(p_organizacion_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
      from public.miembros_organizacion m
     where m.organizacion_id = p_organizacion_id
       and m.usuario_id = (select auth.uid())
       and m.activo
       and m.rol in ('ADMIN', 'MEDICO')
  );
$$;

create or replace function public.comparte_organizacion(p_otro_usuario_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
      from public.miembros_organizacion yo
      join public.miembros_organizacion otro
        on otro.organizacion_id = yo.organizacion_id
       and otro.usuario_id = p_otro_usuario_id
       and otro.activo
     where yo.usuario_id = (select auth.uid())
       and yo.activo
  );
$$;

revoke all on function public.es_miembro(uuid) from public;
revoke all on function public.es_admin(uuid) from public;
revoke all on function public.puede_editar(uuid) from public;
revoke all on function public.comparte_organizacion(uuid) from public;
grant execute on function public.es_miembro(uuid) to authenticated;
grant execute on function public.es_admin(uuid) to authenticated;
grant execute on function public.puede_editar(uuid) to authenticated;
grant execute on function public.comparte_organizacion(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- Ficha familiar y sus secciones
-- ---------------------------------------------------------------------------

create table public.fichas_familiares (
  id uuid primary key default gen_random_uuid(),
  organizacion_id uuid not null references public.organizaciones(id) on delete restrict,
  establecimiento_id bigint references public.establecimientos_salud(id) on delete set null,
  cedula_jefe_hogar text not null default '',
  institucion_sistema text not null default '',
  unidad_operativa text not null default '',
  codigo_uo text not null default '',
  area_numero text not null default '',
  codigo_localizacion text not null default '',
  parroquia_codigo_localizacion text not null default '',
  canton_codigo_localizacion text not null default '',
  provincia_codigo_localizacion text not null default '',
  numero_ficha_familiar text not null default '',
  provincia text not null default '',
  canton text not null default '',
  parroquia text not null default '',
  sector text not null default '',
  manzana text not null default '',
  numero_familia text not null default '',
  direccion_habitual_familia text not null default '',
  barrio text not null default '',
  numero_casa text not null default '',
  comunidad text not null default '',
  grupo_cultural text not null default '',
  nombre_apellido_jefe_familia text not null default '',
  numero_telefono text not null default '',
  fecha_llenado date not null,
  numero_carpeta text not null default '',
  latitud double precision,
  longitud double precision,
  altitud double precision,
  responsable_nombre text not null default '',
  responsable_codigo text not null default '',
  firma_storage_path text,
  estado text not null default 'BORRADOR',
  creado_por uuid default auth.uid() references auth.users(id) on delete set null,
  actualizado_por uuid default auth.uid() references auth.users(id) on delete set null,
  completado_por uuid references auth.users(id) on delete set null,
  creado_en timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1,
  deleted_at timestamptz,
  constraint fichas_id_organizacion_unico unique (id, organizacion_id),
  constraint fichas_estado_valido check (estado in ('BORRADOR', 'COMPLETA', 'ARCHIVADA')),
  constraint fichas_latitud_valida check (latitud is null or latitud between -90 and 90),
  constraint fichas_longitud_valida check (longitud is null or longitud between -180 and 180),
  constraint fichas_version_valida check (version > 0),
  constraint fichas_cedula_formato check (cedula_jefe_hogar = '' or cedula_jefe_hogar ~ '^[0-9]{10,13}$')
);

create index fichas_busqueda_idx
  on public.fichas_familiares (organizacion_id, fecha_llenado desc, estado);
create index fichas_jefe_hogar_idx
  on public.fichas_familiares (organizacion_id, cedula_jefe_hogar);
create index fichas_codigo_uo_idx
  on public.fichas_familiares (organizacion_id, codigo_uo);
create index fichas_sync_idx
  on public.fichas_familiares (organizacion_id, updated_at, id);

create table public.miembros_familia (
  id uuid primary key default gen_random_uuid(),
  organizacion_id uuid not null,
  ficha_id uuid not null,
  grupo_edad text not null default '',
  apellidos_nombres text not null default '',
  parentesco text not null default '',
  fecha_nacimiento date,
  ocupacion text not null default '',
  sexo text not null default '',
  escolaridad text not null default '',
  vacunas_completas boolean,
  salud_bucal_adecuada boolean,
  riesgo_enfermedad_discapacidad text not null default '',
  numero_historia_clinica text not null default '',
  cedula text not null default '',
  creado_por uuid default auth.uid() references auth.users(id) on delete set null,
  creado_en timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1,
  deleted_at timestamptz,
  foreign key (ficha_id, organizacion_id)
    references public.fichas_familiares(id, organizacion_id) on delete cascade,
  constraint miembros_familia_version_valida check (version > 0),
  constraint miembros_familia_cedula_formato check (cedula = '' or cedula ~ '^[0-9]{10,13}$')
);

create index miembros_familia_ficha_idx
  on public.miembros_familia (ficha_id);
create index miembros_familia_cedula_idx
  on public.miembros_familia (organizacion_id, cedula);
create index miembros_familia_sync_idx
  on public.miembros_familia (organizacion_id, updated_at, id);

create table public.embarazadas (
  id uuid primary key default gen_random_uuid(),
  organizacion_id uuid not null,
  ficha_id uuid not null,
  apellidos_nombres text not null default '',
  fecha_ultima_menstruacion date,
  fecha_probable_parto date,
  semanas_gestacion integer,
  dosis_dt_primera boolean not null default false,
  dosis_dt_segunda boolean not null default false,
  dosis_dt_refuerzo boolean not null default false,
  gestas integer,
  partos integer,
  abortos integer,
  cesareas integer,
  antecedentes_patologicos_obstetricos text not null default '',
  creado_por uuid default auth.uid() references auth.users(id) on delete set null,
  creado_en timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1,
  deleted_at timestamptz,
  foreign key (ficha_id, organizacion_id)
    references public.fichas_familiares(id, organizacion_id) on delete cascade,
  constraint embarazadas_semanas_validas check (semanas_gestacion is null or semanas_gestacion between 0 and 45),
  constraint embarazadas_gestas_validas check (gestas is null or gestas >= 0),
  constraint embarazadas_partos_validos check (partos is null or partos >= 0),
  constraint embarazadas_abortos_validos check (abortos is null or abortos >= 0),
  constraint embarazadas_cesareas_validas check (cesareas is null or cesareas >= 0),
  constraint embarazadas_version_valida check (version > 0)
);

create index embarazadas_ficha_idx on public.embarazadas (ficha_id);
create index embarazadas_sync_idx on public.embarazadas (organizacion_id, updated_at, id);

create table public.mortalidad_familiar (
  id uuid primary key default gen_random_uuid(),
  organizacion_id uuid not null,
  ficha_id uuid not null,
  nombre text not null default '',
  parentesco text not null default '',
  edad_al_fallecer integer,
  causa text not null default '',
  creado_por uuid default auth.uid() references auth.users(id) on delete set null,
  creado_en timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1,
  deleted_at timestamptz,
  foreign key (ficha_id, organizacion_id)
    references public.fichas_familiares(id, organizacion_id) on delete cascade,
  constraint mortalidad_edad_valida check (edad_al_fallecer is null or edad_al_fallecer between 0 and 130),
  constraint mortalidad_version_valida check (version > 0)
);

create index mortalidad_ficha_idx on public.mortalidad_familiar (ficha_id);
create index mortalidad_sync_idx on public.mortalidad_familiar (organizacion_id, updated_at, id);

create table public.calificaciones_riesgo (
  id uuid primary key default gen_random_uuid(),
  organizacion_id uuid not null,
  ficha_id uuid not null,
  fecha_calificacion date not null,
  responsable text not null default '',
  total integer not null default 0,
  nivel text not null default 'SIN_RIESGO',
  creado_por uuid default auth.uid() references auth.users(id) on delete set null,
  creado_en timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1,
  deleted_at timestamptz,
  constraint calificaciones_id_organizacion_unico unique (id, organizacion_id),
  foreign key (ficha_id, organizacion_id)
    references public.fichas_familiares(id, organizacion_id) on delete cascade,
  constraint calificaciones_total_valido check (total between 0 and 72),
  constraint calificaciones_nivel_valido check (nivel in ('SIN_RIESGO', 'BAJO', 'MEDIO', 'ALTO')),
  constraint calificaciones_version_valida check (version > 0)
);

create index calificaciones_ficha_idx on public.calificaciones_riesgo (ficha_id);
create index calificaciones_sync_idx on public.calificaciones_riesgo (organizacion_id, updated_at, id);

create table public.valores_riesgo (
  id uuid primary key default gen_random_uuid(),
  organizacion_id uuid not null,
  calificacion_id uuid not null,
  componente integer not null,
  valor integer not null,
  creado_en timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1,
  deleted_at timestamptz,
  foreign key (calificacion_id, organizacion_id)
    references public.calificaciones_riesgo(id, organizacion_id) on delete cascade,
  constraint valores_componente_valido check (componente between 1 and 18),
  constraint valores_valor_valido check (valor between 0 and 4),
  constraint valores_version_valida check (version > 0),
  constraint valores_componente_unico unique (calificacion_id, componente)
);

create index valores_riesgo_calificacion_idx on public.valores_riesgo (calificacion_id);
create index valores_riesgo_sync_idx on public.valores_riesgo (organizacion_id, updated_at, id);

create table public.gestion_riesgo (
  id uuid primary key default gen_random_uuid(),
  organizacion_id uuid not null,
  ficha_id uuid not null,
  fecha_analisis date not null,
  numero integer,
  compromiso_familia text not null default '',
  compromiso_equipo_salud text not null default '',
  fecha_evaluacion date,
  cumplimiento text not null default 'PENDIENTE',
  causas_incumplimiento_observaciones text not null default '',
  responsable text not null default '',
  creado_por uuid default auth.uid() references auth.users(id) on delete set null,
  creado_en timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1,
  deleted_at timestamptz,
  foreign key (ficha_id, organizacion_id)
    references public.fichas_familiares(id, organizacion_id) on delete cascade,
  constraint gestion_numero_valido check (numero is null or numero >= 0),
  constraint gestion_cumplimiento_valido check (cumplimiento in ('PENDIENTE', 'CUMPLIDO', 'PARCIAL', 'INCUMPLIDO')),
  constraint gestion_version_valida check (version > 0)
);

create index gestion_riesgo_ficha_idx on public.gestion_riesgo (ficha_id);
create index gestion_riesgo_sync_idx on public.gestion_riesgo (organizacion_id, updated_at, id);

create table public.contaminacion_ambiental (
  id uuid primary key default gen_random_uuid(),
  organizacion_id uuid not null,
  ficha_id uuid not null,
  fecha_informe date not null,
  tipo_contaminante_descripcion text not null default '',
  causante_contaminacion text not null default '',
  creado_por uuid default auth.uid() references auth.users(id) on delete set null,
  creado_en timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1,
  deleted_at timestamptz,
  foreign key (ficha_id, organizacion_id)
    references public.fichas_familiares(id, organizacion_id) on delete cascade,
  constraint contaminacion_version_valida check (version > 0)
);

create index contaminacion_ficha_idx on public.contaminacion_ambiental (ficha_id);
create index contaminacion_sync_idx on public.contaminacion_ambiental (organizacion_id, updated_at, id);

create table public.lugares_tratamiento (
  id uuid primary key default gen_random_uuid(),
  organizacion_id uuid not null,
  ficha_id uuid not null,
  descripcion text not null default '',
  creado_en timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1,
  deleted_at timestamptz,
  foreign key (ficha_id, organizacion_id)
    references public.fichas_familiares(id, organizacion_id) on delete cascade,
  constraint lugares_version_valida check (version > 0)
);

create index lugares_ficha_idx on public.lugares_tratamiento (ficha_id);
create index lugares_sync_idx on public.lugares_tratamiento (organizacion_id, updated_at, id);

create table public.adjuntos_ficha (
  id uuid primary key default gen_random_uuid(),
  organizacion_id uuid not null,
  ficha_id uuid not null,
  tipo text not null,
  storage_path text not null,
  mime_type text,
  tamano_bytes bigint,
  creado_por uuid default auth.uid() references auth.users(id) on delete set null,
  creado_en timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1,
  deleted_at timestamptz,
  foreign key (ficha_id, organizacion_id)
    references public.fichas_familiares(id, organizacion_id) on delete cascade,
  constraint adjuntos_tipo_unico unique (ficha_id, tipo),
  constraint adjuntos_tamano_valido check (tamano_bytes is null or tamano_bytes >= 0),
  constraint adjuntos_version_valida check (version > 0)
);

create index adjuntos_ficha_idx on public.adjuntos_ficha (ficha_id);
create index adjuntos_sync_idx on public.adjuntos_ficha (organizacion_id, updated_at, id);

create table public.historial_fichas (
  id uuid primary key default gen_random_uuid(),
  organizacion_id uuid not null,
  ficha_id uuid not null,
  numero_ficha text not null default '',
  usuario_id uuid default auth.uid() references auth.users(id) on delete set null,
  usuario_nombre text not null default '',
  accion text not null,
  detalle text not null default '',
  ocurrido_en timestamptz not null,
  registrado_en timestamptz not null default now(),
  foreign key (ficha_id, organizacion_id)
    references public.fichas_familiares(id, organizacion_id) on delete cascade
);

create index historial_ficha_idx on public.historial_fichas (ficha_id, ocurrido_en desc);
create index historial_sync_idx on public.historial_fichas (organizacion_id, registrado_en, id);

-- Incrementa version y fecha del servidor en cada cambio sincronizable.
do $$
declare
  tabla text;
begin
  foreach tabla in array array[
    'fichas_familiares',
    'miembros_familia',
    'embarazadas',
    'mortalidad_familiar',
    'calificaciones_riesgo',
    'valores_riesgo',
    'gestion_riesgo',
    'contaminacion_ambiental',
    'lugares_tratamiento',
    'adjuntos_ficha'
  ] loop
    execute format(
      'create trigger %I before update on public.%I for each row execute function public.actualizar_version_sync()',
      tabla || '_actualizar_version',
      tabla
    );
  end loop;
end;
$$;

-- ---------------------------------------------------------------------------
-- RLS y privilegios
-- ---------------------------------------------------------------------------

alter table public.perfiles enable row level security;
alter table public.establecimientos_salud enable row level security;
alter table public.organizaciones enable row level security;
alter table public.miembros_organizacion enable row level security;
alter table public.invitaciones_organizacion enable row level security;

create policy perfiles_leer_equipo
on public.perfiles for select to authenticated
using (
  id = (select auth.uid())
  or public.comparte_organizacion(id)
);

create policy perfiles_actualizar_propio
on public.perfiles for update to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

create policy establecimientos_leer_activos
on public.establecimientos_salud for select to authenticated
using (activo);

create policy organizaciones_leer_mias
on public.organizaciones for select to authenticated
using (public.es_miembro(id));

create policy organizaciones_actualizar_admin
on public.organizaciones for update to authenticated
using (public.es_admin(id))
with check (public.es_admin(id));

create policy miembros_leer_equipo
on public.miembros_organizacion for select to authenticated
using (public.es_miembro(organizacion_id));

create policy miembros_insertar_admin
on public.miembros_organizacion for insert to authenticated
with check (public.es_admin(organizacion_id));

create policy miembros_actualizar_admin
on public.miembros_organizacion for update to authenticated
using (public.es_admin(organizacion_id))
with check (public.es_admin(organizacion_id));

create policy miembros_eliminar_admin
on public.miembros_organizacion for delete to authenticated
using (public.es_admin(organizacion_id) and usuario_id <> (select auth.uid()));

do $$
declare
  tabla text;
begin
  foreach tabla in array array[
    'fichas_familiares',
    'miembros_familia',
    'embarazadas',
    'mortalidad_familiar',
    'calificaciones_riesgo',
    'valores_riesgo',
    'gestion_riesgo',
    'contaminacion_ambiental',
    'lugares_tratamiento',
    'adjuntos_ficha'
  ] loop
    execute format('alter table public.%I enable row level security', tabla);
    execute format(
      'create policy %I on public.%I for select to authenticated using (public.es_miembro(organizacion_id))',
      tabla || '_leer_miembros', tabla
    );
    execute format(
      'create policy %I on public.%I for insert to authenticated with check (public.puede_editar(organizacion_id))',
      tabla || '_insertar_editores', tabla
    );
    execute format(
      'create policy %I on public.%I for update to authenticated using (public.puede_editar(organizacion_id)) with check (public.puede_editar(organizacion_id))',
      tabla || '_actualizar_editores', tabla
    );
  end loop;
end;
$$;

alter table public.historial_fichas enable row level security;

create policy historial_leer_miembros
on public.historial_fichas for select to authenticated
using (public.es_miembro(organizacion_id));

create policy historial_insertar_editores
on public.historial_fichas for insert to authenticated
with check (
  public.puede_editar(organizacion_id)
  and usuario_id = (select auth.uid())
);

grant usage on schema public to authenticated;
grant select, update on public.perfiles to authenticated;
grant select on public.establecimientos_salud to authenticated;
grant select, update on public.organizaciones to authenticated;
grant select, insert, update, delete on public.miembros_organizacion to authenticated;
grant select, insert, update on
  public.fichas_familiares,
  public.miembros_familia,
  public.embarazadas,
  public.mortalidad_familiar,
  public.calificaciones_riesgo,
  public.valores_riesgo,
  public.gestion_riesgo,
  public.contaminacion_ambiental,
  public.lugares_tratamiento,
  public.adjuntos_ficha
to authenticated;
grant select, insert on public.historial_fichas to authenticated;

-- ---------------------------------------------------------------------------
-- RPC de incorporacion de usuarios
-- ---------------------------------------------------------------------------

create or replace function public.crear_organizacion_inicial(
  p_nombre text,
  p_codigo text,
  p_establecimiento_id bigint default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_usuario uuid := auth.uid();
  v_organizacion uuid;
  v_codigo text := upper(btrim(p_codigo));
begin
  if v_usuario is null then
    raise exception 'Debes iniciar sesion.' using errcode = '42501';
  end if;

  if char_length(btrim(p_nombre)) not between 3 and 120 then
    raise exception 'El nombre debe tener entre 3 y 120 caracteres.' using errcode = '22023';
  end if;

  if v_codigo !~ '^[A-Z0-9_-]{3,30}$' then
    raise exception 'El codigo debe tener entre 3 y 30 letras, numeros, guiones o guion bajo.' using errcode = '22023';
  end if;

  if exists (
    select 1 from public.miembros_organizacion
     where usuario_id = v_usuario and activo
  ) then
    raise exception 'El usuario ya pertenece a una organizacion activa.' using errcode = '23505';
  end if;

  if p_establecimiento_id is not null and not exists (
    select 1 from public.establecimientos_salud
     where id = p_establecimiento_id and activo
  ) then
    raise exception 'El establecimiento seleccionado no existe o esta inactivo.' using errcode = '23503';
  end if;

  insert into public.organizaciones (nombre, codigo, creado_por)
  values (btrim(p_nombre), v_codigo, v_usuario)
  returning id into v_organizacion;

  insert into public.miembros_organizacion (
    organizacion_id, usuario_id, establecimiento_id, rol, activo, creado_por
  ) values (
    v_organizacion, v_usuario, p_establecimiento_id, 'ADMIN', true, v_usuario
  );

  return v_organizacion;
end;
$$;

create or replace function public.crear_invitacion(
  p_organizacion_id uuid,
  p_correo text default null,
  p_rol text default 'MEDICO',
  p_establecimiento_id bigint default null,
  p_horas_vigencia integer default 168
)
returns table (codigo text, expira_en timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_codigo text;
  v_expira timestamptz;
  v_rol text := upper(btrim(p_rol));
begin
  if not public.es_admin(p_organizacion_id) then
    raise exception 'Solo un administrador puede invitar usuarios.' using errcode = '42501';
  end if;

  if v_rol not in ('ADMIN', 'MEDICO', 'ESTADISTICA') then
    raise exception 'Rol no valido.' using errcode = '22023';
  end if;

  if p_horas_vigencia not between 1 and 720 then
    raise exception 'La vigencia debe estar entre 1 y 720 horas.' using errcode = '22023';
  end if;

  if p_establecimiento_id is not null and not exists (
    select 1 from public.establecimientos_salud
     where id = p_establecimiento_id and activo
  ) then
    raise exception 'El establecimiento seleccionado no existe o esta inactivo.' using errcode = '23503';
  end if;

  v_codigo := upper(encode(extensions.gen_random_bytes(8), 'hex'));
  v_expira := now() + make_interval(hours => p_horas_vigencia);

  insert into public.invitaciones_organizacion (
    organizacion_id,
    correo,
    rol,
    establecimiento_id,
    codigo_hash,
    expira_en,
    creado_por
  ) values (
    p_organizacion_id,
    nullif(lower(btrim(p_correo)), ''),
    v_rol,
    p_establecimiento_id,
    extensions.digest(v_codigo, 'sha256'),
    v_expira,
    auth.uid()
  );

  return query select v_codigo, v_expira;
end;
$$;

create or replace function public.aceptar_invitacion(p_codigo text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_usuario uuid := auth.uid();
  v_correo text;
  v_invitacion public.invitaciones_organizacion%rowtype;
begin
  if v_usuario is null then
    raise exception 'Debes iniciar sesion.' using errcode = '42501';
  end if;

  select lower(email) into v_correo
    from auth.users
   where id = v_usuario;

  select * into v_invitacion
    from public.invitaciones_organizacion
   where codigo_hash = extensions.digest(upper(btrim(p_codigo)), 'sha256')
     and usado_en is null
     and expira_en > now()
   for update;

  if not found then
    raise exception 'El codigo es invalido, ya fue usado o expiro.' using errcode = '22023';
  end if;

  if v_invitacion.correo is not null
     and lower(v_invitacion.correo) <> v_correo then
    raise exception 'La invitacion pertenece a otro correo.' using errcode = '42501';
  end if;

  insert into public.miembros_organizacion (
    organizacion_id, usuario_id, establecimiento_id, rol, activo, creado_por
  ) values (
    v_invitacion.organizacion_id,
    v_usuario,
    v_invitacion.establecimiento_id,
    v_invitacion.rol,
    true,
    v_invitacion.creado_por
  )
  on conflict (organizacion_id, usuario_id) do update
    set establecimiento_id = excluded.establecimiento_id,
        rol = excluded.rol,
        activo = true,
        updated_at = now();

  update public.invitaciones_organizacion
     set usado_en = now(), usado_por = v_usuario
   where id = v_invitacion.id;

  return v_invitacion.organizacion_id;
end;
$$;

revoke all on function public.crear_organizacion_inicial(text, text, bigint) from public;
revoke all on function public.crear_invitacion(uuid, text, text, bigint, integer) from public;
revoke all on function public.aceptar_invitacion(text) from public;
grant execute on function public.crear_organizacion_inicial(text, text, bigint) to authenticated;
grant execute on function public.crear_invitacion(uuid, text, text, bigint, integer) to authenticated;
grant execute on function public.aceptar_invitacion(text) to authenticated;

-- ---------------------------------------------------------------------------
-- Storage privado para firmas y adjuntos de fichas
-- Ruta obligatoria: organizacion_uuid/ficha_uuid/nombre_archivo
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'fichas-adjuntos',
  'fichas-adjuntos',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'application/pdf']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create policy adjuntos_storage_leer
on storage.objects for select to authenticated
using (
  bucket_id = 'fichas-adjuntos'
  and public.es_miembro(public.uuid_seguro((storage.foldername(name))[1]))
);

create policy adjuntos_storage_insertar
on storage.objects for insert to authenticated
with check (
  bucket_id = 'fichas-adjuntos'
  and public.puede_editar(public.uuid_seguro((storage.foldername(name))[1]))
);

create policy adjuntos_storage_actualizar
on storage.objects for update to authenticated
using (
  bucket_id = 'fichas-adjuntos'
  and public.puede_editar(public.uuid_seguro((storage.foldername(name))[1]))
)
with check (
  bucket_id = 'fichas-adjuntos'
  and public.puede_editar(public.uuid_seguro((storage.foldername(name))[1]))
);

create policy adjuntos_storage_eliminar
on storage.objects for delete to authenticated
using (
  bucket_id = 'fichas-adjuntos'
  and public.puede_editar(public.uuid_seguro((storage.foldername(name))[1]))
);

comment on table public.fichas_familiares is
  'Ficha familiar sincronizada desde SQLite cifrado. UUID evita colisiones entre dispositivos.';
comment on column public.fichas_familiares.version is
  'Version del servidor usada para detectar conflictos de sincronizacion.';
comment on column public.fichas_familiares.deleted_at is
  'Marca de borrado logico que permite propagar eliminaciones a dispositivos offline.';
